# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_type', models.CharField(max_length=20)),
                ('pn_num', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=20)),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Asik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_ip', models.GenericIPAddressField()),
                ('lmp_eth_ip', models.GenericIPAddressField()),
                ('serial_type', models.CharField(max_length=20)),
                ('pn_num', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
