# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asik',
            name='test_column',
            field=models.CharField(default='111', max_length=50),
        ),
        migrations.AlterField(
            model_name='asik',
            name='lmp_eth_ip',
            field=models.GenericIPAddressField(default='192.168.255.1'),
        ),
    ]
