# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_asik_test_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asik',
            old_name='pn_num',
            new_name='pn_num_test',
        ),
    ]
