# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20190131_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asik',
            name='pn_num',
            field=models.TextField(default='3333', max_length=100),
        ),
    ]
