# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20190131_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asik',
            name='pn_num',
            field=models.CharField(max_length=100),
        ),
    ]
