# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20190131_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='abil',
            name='slot',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='asik',
            name='slot',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
