# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190131_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicalBTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asik_id', models.IntegerField(default=0)),
                ('abil_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='abil',
            name='added_time',
        ),
        migrations.RemoveField(
            model_name='asik',
            name='added_time',
        ),
        migrations.AddField(
            model_name='asik',
            name='gps_id',
            field=models.IntegerField(default=0),
        ),
    ]
