# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20190131_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalbts',
            name='owner',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='abil',
            name='owner',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
