# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20190208_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asik',
            name='gps_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
