# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_auto_20190211_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='pn',
            field=models.CharField(default='FYGB', max_length=21),
        ),
    ]
