# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_auto_20190211_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalbts',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abil',
            name='rru',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Rru'),
        ),
        migrations.AlterField(
            model_name='asik',
            name='gps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Gps'),
        ),
        migrations.AlterField(
            model_name='classicalbts',
            name='abil_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Abil'),
        ),
        migrations.AlterField(
            model_name='classicalbts',
            name='amia_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Amia'),
        ),
        migrations.AlterField(
            model_name='classicalbts',
            name='asik_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Asik'),
        ),
    ]
