# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_auto_20190212_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='10.1.1.3', unique=True)),
                ('sn', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(default='admin', max_length=50)),
            ],
        ),
    ]
