# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_pb'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalbts',
            name='pb_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Pb'),
        ),
        migrations.AddField(
            model_name='classicalbts',
            name='pb_port',
            field=models.CharField(blank=True, choices=[('1', 'PORT_1'), ('2', 'PORT_2'), ('3', 'PORT_3'), ('4', 'PORT_4'), ('5', 'PORT_5'), ('6', 'PORT_6'), ('7', 'PORT_7'), ('8', 'PORT_8')], max_length=20, null=True),
        ),
    ]
